"""Research executor — routes to Claude agent or OpenRouter backend."""

from __future__ import annotations

from typing import TYPE_CHECKING

from aii_lib.abilities.endpoint_names import (
    AII_WEB_FETCH,
    AII_WEB_FETCH_GREP,
    AII_WEB_SEARCH,
)
from aii_lib.run import emit

from aii_lib import setup_workspace, start_task

if TYPE_CHECKING:
    from pathlib import Path

    from aii_pipeline.prompts.steps._3_invention_loop._2_gen_plan.out_schema import (
        BasePlan,
    )
    from aii_pipeline.prompts.steps._3_invention_loop._3_gen_art.out_schema import (
        BaseArtifact,
    )
    from aii_pipeline.utils import PipelineConfig

RESEARCH_TOOLS = [AII_WEB_SEARCH, AII_WEB_FETCH, AII_WEB_FETCH_GREP]


def write_research_report(research_result: dict, workspace_dir: Path) -> None:
    """Write research_report.md to workspace from result dict."""
    title = research_result.get("title", "Research")
    summary = research_result.get("summary", "")
    answer = research_result.get("answer", "")
    sources = research_result.get("sources", [])
    follow_up = research_result.get("follow_up_questions", [])

    md = f"# {title}\n\n"
    if summary:
        md += f"## Summary\n\n{summary}\n\n"
    if answer:
        md += f"## Research Findings\n\n{answer}\n\n"
    if sources:
        md += "## Sources\n\n"
        for src in sources:
            idx = src.get("index", "")
            url = src.get("url", "")
            src_title = src.get("title", "")
            src_summary = src.get("summary", "")
            prefix = f"[{idx}] "
            md += f"{prefix}[{src_title}]({url})" if url else f"{prefix}{src_title}"
            if src_summary:
                md += f" — {src_summary}"
            md += "\n\n"
    if follow_up:
        md += "## Follow-up Questions\n\n"
        for q in follow_up:
            md += f"- {q}\n"
        md += "\n"
    md += "---\n*Generated by AI Inventor Pipeline*\n"
    (workspace_dir / "research_report.md").write_text(md, encoding="utf-8")


async def execute_research(
    plan: BasePlan,
    artifacts: list[BaseArtifact],
    config: PipelineConfig,
    run_dir: Path,
    iteration: int = 1,
    research_idx: int = 0,
    task_id: str | None = None,
    task_name: str | None = None,
    parent_module_id: str = "",
    user_uploads_path: str = "",
) -> tuple[dict, bool]:
    """Execute a research plan — routes to Claude agent or OpenRouter."""
    effective_task_name = task_name or task_id or f"research_workspace_idx{research_idx}"
    workspace_dir = run_dir / effective_task_name
    setup_workspace(workspace_dir)
    effective_task_id = start_task(effective_task_name, parent_module_id)

    # Log dependencies
    if plan.artifact_dependencies:
        dep_ids = {d.id for d in plan.artifact_dependencies}
        dep_artifacts = [a for a in artifacts if a.id in dep_ids]
        dep_info = [(d.id, d.title, bool(d.summary)) for d in dep_artifacts]
        emit.status_private_debug(f"Research deps: {dep_info}")

    research_cfg = config.invention_loop.execute.research
    emit.status_private_info(f"Executing RESEARCH: {plan.title}")
    emit.status_private_info(f"Workspace: {workspace_dir}")

    if research_cfg.use_claude_agent:
        from ._research.claude import execute_research_claude

        return await execute_research_claude(
            plan,
            artifacts,
            config,
            workspace_dir,
            task_id=effective_task_id,
            task_name=effective_task_name,
            user_uploads_path=user_uploads_path,
        )
    from ._research.openrouter import execute_research_openrouter

    return await execute_research_openrouter(
        plan,
        artifacts,
        config,
        workspace_dir,
        task_id=effective_task_id,
        task_name=effective_task_name,
        user_uploads_path=user_uploads_path,
    )
