"""README generation with Colab links for deployed repos."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from aii_pipeline.prompts.steps._4_gen_paper_repo._3_gen_art_demo.schema_code import (
    LeanDemo,
)
from aii_pipeline.steps._4_gen_paper_repo._3_gen_art_demo import github_to_colab_url

if TYPE_CHECKING:
    from aii_pipeline.prompts.steps._3_invention_loop._3_gen_art.out_schema import (
        BaseArtifact,
    )


def write_artifact_readme(
    artifact_dir: Path,
    artifact: BaseArtifact | None,
    demo,
    files_added: list[str],
) -> None:
    """Write a README.md into an artifact's repo folder.

    Includes: title, type, summary, dependency info, and demo/src pointers.
    """
    folder_name = artifact_dir.name
    title = (artifact.title if artifact else demo.title) or folder_name
    art_type = artifact.type.value if artifact else "unknown"
    layman_summary = (artifact.layman_summary if artifact else "") or ""
    summary = (artifact.summary if artifact else demo.summary) or ""
    art_id = artifact.id if artifact else demo.id

    lines = [
        f"# {title}",
        "",
        "`demo/` — Self-contained demo (Colab-ready notebook or markdown). Run without setup.  ",
        "`src/` — Full source code, data, and outputs from the experiment execution.",
        "",
        f"**Type:** {art_type}  ",
        f"**ID:** `{art_id}`",
        "",
    ]

    if layman_summary:
        lines += ["## Layman Summary", "", layman_summary, ""]

    if summary:
        lines += ["## Full Summary", "", summary, ""]

    if artifact:
        if artifact.in_dependencies:
            lines += [
                "## Dependencies",
                "",
                *(
                    f"- `{dep.id}` — {dep.label}" if dep.label else f"- `{dep.id}`"
                    for dep in artifact.in_dependencies
                ),
                "",
            ]

        if artifact.out_expected_files:
            lines += [
                "## Output Files",
                "",
                *(f"- `{f}`" for f in artifact.out_expected_files),
                "",
            ]

        if artifact.out_demo_files:
            lines += [
                "## Demo Files",
                "",
                *(f"- **{f.path}** — {f.description}" for f in artifact.out_demo_files),
                "",
            ]

    lines += [
        "---",
        "*Generated by AI Inventor Pipeline*",
        "",
    ]

    readme_path = artifact_dir / "README.md"
    readme_path.write_text("\n".join(lines), encoding="utf-8")
    files_added.append(f"{folder_name}/README.md")


def generate_readme_with_colab_links(
    repo_url: str,
    prepared_artifacts: list,
    artifacts: list[BaseArtifact],
    has_paper_pdf: bool = False,
    has_paper_latex: bool = False,
    aid_to_folder: dict | None = None,
) -> str:
    """Generate README.md with Colab links for notebooks.

    ``aid_to_folder`` is keyed by ``(iteration, aid)`` — same aid recurs
    across invention_loop iters (#14 in the errors doc) and each iter's
    artifact lives at ``iter_<N>/<aid>/`` in the published repo.
    """
    # Normalize repo URL
    repo_url = repo_url.rstrip("/")
    if repo_url.endswith(".git"):
        repo_url = repo_url[:-4]
    artifacts_by_key = {(a.iteration, a.id): a for a in artifacts}

    readme = """# AI Invention Research Repository

This repository contains artifacts from an AI-generated research project.

"""

    # Paper section
    if has_paper_pdf or has_paper_latex:
        readme += """## Research Paper

"""
        if has_paper_pdf:
            pdf_url = f"{repo_url}/blob/main/paper.pdf"
            pdf_badge = (
                f"[![Download PDF](https://img.shields.io/badge/Download-PDF-red)]({pdf_url})"
            )
            readme += f"{pdf_badge} "

        if has_paper_latex:
            latex_url = f"{repo_url}/tree/main/paper_latex"
            latex_badge = (
                f"[![LaTeX Source](https://img.shields.io/badge/LaTeX-Source-orange)]({latex_url})"
            )
            readme += f"{latex_badge}"

        readme += "\n\n"

    readme += """## Artifacts

"""

    # Group artifacts by artifact type (not demo type)
    folder_map = aid_to_folder or {}
    # Ordered sections: research, datasets, experiments, proofs, evaluations
    sections: dict[str, list[dict]] = {
        "research": [],
        "dataset": [],
        "experiment": [],
        "proof": [],
        "evaluation": [],
    }

    for prep in prepared_artifacts:
        aid = prep.id
        key = (prep.iteration, aid)
        folder_name = folder_map.get(key) or f"iter_{prep.iteration}/{aid}"
        demo_type = prep.type.value
        artifact = artifacts_by_key.get(key)
        short_desc = artifact.title if artifact else aid
        art_type = artifact.type.value if artifact else "experiment"

        entry: dict = {"id": aid, "folder": folder_name, "desc": short_desc}

        if isinstance(prep, LeanDemo) and prep.playground_url:
            entry["demo_kind"] = "lean"
            entry["playground_url"] = prep.playground_url
        elif demo_type == "code":
            demo_path = Path(prep.demo_path)
            if demo_path.is_dir():
                ipynb_files = list(demo_path.glob("*.ipynb"))
                notebook_name = ipynb_files[0].name if ipynb_files else "code_demo.ipynb"
            else:
                notebook_name = demo_path.name
            rel_path_str = f"{folder_name}/demo/{notebook_name}"
            github_url = f"{repo_url}/blob/main/{rel_path_str}"
            entry["demo_kind"] = "colab"
            entry["colab_url"] = github_to_colab_url(github_url)
        else:
            demo_path = Path(prep.demo_path)
            rel_path_str = f"{folder_name}/demo/{demo_path.name}"
            entry["demo_kind"] = "markdown"
            entry["github_url"] = f"{repo_url}/blob/main/{rel_path_str}"

        sections.setdefault(art_type, []).append(entry)

    section_titles = {
        "research": "Research",
        "dataset": "Datasets",
        "experiment": "Experiments",
        "proof": "Proofs",
        "evaluation": "Evaluations",
    }

    first_section = True
    for art_type, title in section_titles.items():
        items = sections.get(art_type, [])
        if not items:
            continue
        prefix = "" if first_section else "\n"
        readme += f"""{prefix}### {title}

| Title | Demo | Source Code |
|-------|------|-------------|
"""
        first_section = False
        for item in items:
            source_badge = f"[![Source Code](https://img.shields.io/badge/Source_Code-2962FF)]({repo_url}/tree/main/{item['folder']}/src)"
            _desc = item["desc"].replace("|", "\\|")
            _desc = f"{_desc[:60]}..." if len(_desc) > 60 else _desc
            folder_url = f"{repo_url}/tree/main/{item['folder']}"

            if item["demo_kind"] == "colab":
                demo_badge = f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({item['colab_url']})"
            elif item["demo_kind"] == "lean":
                demo_badge = f"[![Verify in Lean](https://img.shields.io/badge/Lean_4-Verify_Proof-blue)]({item['playground_url']})"
            else:
                demo_badge = f"[![View Research](https://img.shields.io/badge/View-Research-green)]({item['github_url']})"

            readme += f"| [{_desc}]({folder_url}) | {demo_badge} | {source_badge} |\n"

    repo_name = repo_url.split("/")[-1] if "/" in repo_url else "repo"
    readme += f"""
## Repository Structure

Each artifact has its own folder with source code and demos:

```
.
├── <artifact_id>/
│   ├── src/                     # Full workspace from execution
│   │   ├── method.py            # Main implementation
│   │   ├── method_out.json      # Full output data
│   │   ├── mini_method_out.json # Mini version (3 examples)
│   │   └── ...                  # All execution artifacts
│   └── demo/                    # Self-contained demos
│       └── method_code_demo.ipynb # Colab-ready notebook (code + data inlined)
├── <another_artifact>/
│   ├── src/
│   └── demo/
├── paper.pdf                    # Research paper
├── paper_latex/                 # LaTeX source files
└── README.md
```

## Running Notebooks

### Option 1: Google Colab (Recommended)

Click the "Open in Colab" badges above to run notebooks directly in your browser.
No installation required!

### Option 2: Local Jupyter

```bash
# Clone the repo
git clone {repo_url}
cd {repo_name}

# Install dependencies
pip install jupyter

# Run any artifact's demo notebook
jupyter notebook <artifact_folder>/demo/
```

## Source Code

The original source files are in each artifact's `src/` folder.
These files may have external dependencies - use the demo notebooks for a self-contained experience.

---
*Generated by AI Inventor Pipeline - Automated Research Generation*
"""

    return readme
