"""Research artifact → markdown demo conversion.

Converts research artifacts into formatted markdown
with title, summary, answer (with citations), sources, and follow-up questions.
No LLM needed — deterministic field extraction + string formatting.

Reads from workspace research_out.json since the artifact pool only stores
BaseArtifact fields (research-specific fields like answer/sources are not
preserved in the pool).

Used for: research artifact type.
"""

import json
from pathlib import Path


def create_research_markdown(artifact, workspace_path: Path | None = None) -> str:
    """Create a formatted markdown demo from a research artifact.

    Reads research-specific fields (answer, sources, follow_up_questions) from
    workspace/research_out.json since the pool stores BaseArtifact which doesn't
    have these fields. Falls back to artifact model fields if available.

    Args:
        artifact: BaseArtifact (or ResearchArtifact) with at least title/summary.
        workspace_path: Path to artifact workspace containing research_out.json.

    Returns:
        Formatted markdown string.
    """
    if artifact is None:
        raise ValueError("artifact must not be None")

    title = artifact.title or artifact.id
    summary = artifact.summary

    # Research-specific fields: read from workspace research_out.json
    answer = None
    sources = None
    follow_up = None

    # Try workspace file first (always available, has full data)
    if workspace_path:
        research_json = Path(workspace_path) / "research_out.json"
        if research_json.exists():
            try:
                data = json.loads(research_json.read_text(encoding="utf-8"))
                answer = data.get("answer")
                sources = data.get("sources")
                follow_up = data.get("follow_up_questions")
                # Use title/summary from JSON if artifact fields are empty
                if not title or title == artifact.id:
                    title = data.get("title", title)
                if not summary:
                    summary = data.get("summary")
            except (json.JSONDecodeError, OSError):
                pass

    # Fallback: try artifact model fields (works if artifact is ResearchArtifact)
    if answer is None:
        answer = getattr(artifact, "answer", None)
    if sources is None:
        sources = getattr(artifact, "sources", None)
    if follow_up is None:
        follow_up = getattr(artifact, "follow_up_questions", None)

    md = f"# {title}\n\n"

    # Summary
    if summary:
        md += f"## Summary\n\n{summary}\n\n"

    # Research findings (answer with inline citations)
    if answer:
        md += f"## Research Findings\n\n{answer}\n\n"

    # Sources
    if sources:
        md += "## Sources\n\n"
        for src in sources:
            # Handle both dict (from JSON) and model object (from ResearchArtifact)
            if isinstance(src, dict):
                idx = src.get("index", "")
                url = src.get("url", "")
                src_title = src.get("title", "")
                src_summary = src.get("summary", "")
            else:
                idx = src.index
                url = src.url
                src_title = src.title
                src_summary = src.summary

            prefix = f"[{idx}] "
            if url:
                md += f"{prefix}[{src_title}]({url})"
            else:
                md += f"{prefix}{src_title}"
            if src_summary:
                md += f" — {src_summary}"
            md += "\n\n"

    # Follow-up questions
    if follow_up:
        md += "## Follow-up Questions\n\n"
        for q in follow_up:
            md += f"- {q}\n"
        md += "\n"

    md += "---\n*Generated by AI Inventor Pipeline*\n"
    return md
